version: "3"
services:
  mongo:
    container_name: ma-mongo
    image: mongo
    restart: always
    ports:
      - "27017"
    networks:
      - default
    volumes:
      - ./backend/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./backend/docker-setup/mongo/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=MatterStore-Dev
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

  backend:
    container_name: ms-node
    build:
      context: ./backend
      dockerfile: docker-setup/node/production/Dockerfile
    networks:
      - default
      - frontend
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "4000"

  frontend:
    container_name: ms-react
    build:
      context: ./frontend
      dockerfile: docker-setup/react/production/Dockerfile
    networks:
      - frontend
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    tty: true
    stdin_open: true
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    name: ms-backend
  frontend:
    name: ms-frontend
