version: "3"

services:
  mongo:
    container_name: ms-mongo
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - ./backend/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./backend/docker-setup/mongo/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=MatterStore-Dev
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

  backend:
    container_name: ms-node
    build:
      context: ./backend
      dockerfile: docker-setup/node/development/Dockerfile
    networks:
      - bdefault
      - frontend
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env.development
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "8080:4000"

frontend:
    container_name: ms-react
    build:
      context: ./frontend
      dockerfile: docker-setup/react/Dockerfile
    networks:
      - frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

  loadbalancer:
    container_name: ms-nginx
    build:
      context: ./frontend/docker-setup/nginx
      dockerfile: ./Dockerfile
    networks:
      - frontend
      - default
    tty: true
    stdin_open: true
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    name: ms-backend
  frontend:
    name: ms-frontend